version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: zsm
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

homebrew_casks:
  - name: zsm
    repository:
      owner: mdsakalu
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/mdsakalu/zmx-session-manager"
    description: "TUI session manager for zmx"
    binaries:
      - zsm

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
